# -*- coding: utf-8 -*-
"""Day 2_2 - Data Visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XJyO0ZtnrSveMpBNk05cGPf7HLT6zQzK
"""

import matplotlib.pyplot as plt

##### Line Plot
x = [1,2,3,4,5]
y = [3,4,1,2,7]
plt.plot(x,y)
plt.show()

##### Line Plot
x = [1,2,3,4,5]
y = [3,4,1,2,7]
plt.figure(figsize=(6,4))   ### width,height
plt.title("Line Plot Graph",fontsize=15)
plt.xlabel("Time",fontsize=12)
plt.ylabel("Velocity",fontsize=12)
plt.plot(x,y,label="Line Plot",color="purple")
plt.grid()
plt.legend(loc=2)
plt.show()

##### Bar Plot
x = [1,2,3,4,5]
y = [30,40,10,20,70]
plt.figure(figsize=(6,4))   ### width,height
plt.title("Bar Plot Graph",fontsize=15)
plt.bar(x,y,label="Bar Plot",color="purple")
plt.plot(x,y,label="Line Plot",color="purple")
plt.legend(loc=2)
plt.show()

##### Scatter Plot
x = [1,2,3,4,5,6,7,8,9,10]
y = [3,4,1,2,7,1,3,5,6,7]
plt.figure(figsize=(6,4))   ### width,height
plt.title("Scatter Plot Graph",fontsize=15)
plt.scatter(x,y,label="Scatter Plot",color="purple",s=100,marker="*")
plt.legend(loc=2)
plt.show()

#### Histogram
import numpy as np
np.random.seed(1)
data = np.random.randint(1,100,50)
plt.hist(data,rwidth=0.9,range=(0,50),bins=7)
plt.show()
data

#### Pie Chart
plt.figure(figsize=(7,7))
slices = [50,90,80,10,35]
activities = ["Reading","Sleeping","Gaming","Cooking","Travelling"]
cols = ["red","purple","blue","green","yellow"]
plt.pie(slices,labels=activities,colors=cols
        ,autopct="%1.2f%%",explode=(0,0,0,0.3,0))
plt.show()

#### Pie Chart
plt.figure(figsize=(7,7))
slices = [50,90,80,10,35]
activities = ["Reading","Sleeping","Gaming","Cooking","Travelling"]
cols = ["red","purple","blue","green","yellow"]
plt.pie(slices,labels=activities,colors=cols
        ,autopct="%1.2f%%",explode=(0,0,0,0.3,0))
plt.show()
plt.savefig("bar.eps")

####### Plot a trigonometric equation
import numpy as np
t = np.arange(0.0,2.0,0.01)
v = 1 + np.cos(2 * np.pi * t)
plt.plot(t,v)
plt.grid()
plt.show()

a=[]
b=[]
for i in range(100):
  a.append(i)
  b.append(100-i)
plt.plot(a,b)
plt.show()

##### Sub Plot
import numpy as np
t1 = np.arange(0.0,2.0,0.01)
v1 = 1 + np.cos(2 * np.pi * t1)
t2 = np.arange(0.0,5.0,0.01)
v2 = 1 + np.cos(2 * np.pi * t2)
plt.subplot(2,1,1)
plt.plot(t1,v1)
plt.subplot(2,1,2)
plt.plot(t2,v2)
plt.grid()
plt.show()

