# -*- coding: utf-8 -*-
"""Day 4 - KNN - IRIS Image Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jqvOyDseJq-89Mz58KMV8Thn3Fk3DLPq
"""

import pandas as pd

path = "https://raw.githubusercontent.com/umangkejriwal1122/Machine-Learning/master/Data%20Sets/Iris.csv"
data = pd.read_csv(path)
data.head()

len(data)

data['Species'].unique()

#### Divide the data into x and y
x = data.iloc[:,1:5].values
y = data.iloc[:,5].values

x

y

### Divide the data into train and test
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20)

#### Scaling/Normalization of input Data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtrain = sc.fit_transform(xtrain)
xtest = sc.fit_transform(xtest)

#### Build the model
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 5)

#### Train the model
model.fit(xtrain,ytrain)

ypred = model.predict(xtest)
ypred

ytest

##### Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest,ypred)
cm

(cm.diagonal().sum())/cm.sum() * 100

##### Accuracy
from sklearn.metrics import accuracy_score
a = accuracy_score(ytest,ypred)
a

model.predict([[1.2,2.3,4.5,2.2]])

