# -*- coding: utf-8 -*-
"""Day 4 - Web Scraping Basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y9ow2-ARUmjyLcCqMyo7Ew-alA0g-D9l
"""

import requests   ### loading the url (get the request of url)
from bs4 import BeautifulSoup  ### Webscraping

url = "http://15.206.143.222/webscrap/demo1.html"

page = requests.get(url)
page

page.content

soup = BeautifulSoup(page.content,'html.parser')
print(soup.prettify())

html = list(soup.children)[2]
html

body = list(html.children)[3]
body

p = list(body.children)[1]
p

data = p.get_text()
data

##################################################

url = "http://15.206.143.222/webscrap/demo2.html"

page = requests.get(url)
page

soup = BeautifulSoup(page.content,'html.parser')
print(soup.prettify())

p = soup.find('p')
p

p = soup.find_all('p')
p

p[1].get_text()

################################################

url = "http://15.206.143.222/webscrap/demo3.html"

page = requests.get(url)
page

soup = BeautifulSoup(page.content,'html.parser')
print(soup.prettify())

soup.find_all('p', class_= "inner-text")

soup.find_all('p', id = "first")

soup.find_all(id = "first")

soup.select('div p')

soup.select('div p.first-item')

soup.select('div p#first')



