# -*- coding: utf-8 -*-
"""Lab 1 - Amazon Producr Review Scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JfOs-hkJVyAStu3g1xsnb0fBc5EoFERK
"""

import requests
from bs4 import BeautifulSoup

url = "https://www.amazon.in/Test-Exclusive-746/product-reviews/B07DJHXTLJ/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
page = requests.get(url)
page

soup = BeautifulSoup(page.content,'html.parser')
print(soup.prettify())

names = soup.find_all('span',class_='a-profile-name')[2:]
names

#cust_name = [val.get_text() for val in names]
cust_name = []
for val in names:
  cust_name.append(val.get_text())
cust_name

rating = soup.find_all('span',class_='a-icon-alt')[3:]
rating

cust_rating = [val.get_text() for val in rating]
cust_rating

title=soup.select('a.review-title span')
title

titles = [val.get_text() for val in title]
titles

date = soup.find_all('span',class_='review-date')[2:]
len(date)

dates = [val.get_text() for val in date]
dates

review=soup.select('span.review-text span')
len(review)

reviews = [val.get_text() for val in review]
reviews

len(cust_name)

len(cust_rating)

len(dates)

len(titles)

len(reviews)

import pandas as pd
df = pd.DataFrame()
df["Date"] = dates
df['Customer Name'] = cust_name
df['Title'] = titles
df["Ratings"] = cust_rating
df['Review'] = reviews
df

df.to_csv('reviews.csv')

